# Site settings
title: English Heritage
client:
  name: English Heritage
  link: http://www.english-heritage.org.uk/
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Whether you’re heading to quintessential English countryside for a superlative getaway, or you fancy a day trip away from home to fill a sunny weekend, discover over 5,000 years of history with English Heritage and Secret Escapes.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/english-heritage" # the subpath of your site, e.g. /blog/
img:     "/english-heritage/_assets/img"
css:     "/english-heritage/_assets/css"
js:      "/english-heritage/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed